// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vncarbon/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetVncarbonRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetVncarbonRequest) Reset()         { *m = QueryGetVncarbonRequest{} }
func (m *QueryGetVncarbonRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetVncarbonRequest) ProtoMessage()    {}
func (*QueryGetVncarbonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_286c366297741c32, []int{0}
}
func (m *QueryGetVncarbonRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVncarbonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVncarbonRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVncarbonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVncarbonRequest.Merge(m, src)
}
func (m *QueryGetVncarbonRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVncarbonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVncarbonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVncarbonRequest proto.InternalMessageInfo

func (m *QueryGetVncarbonRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetVncarbonResponse struct {
	Vncarbon *Vncarbon `protobuf:"bytes,1,opt,name=Vncarbon,proto3" json:"Vncarbon,omitempty"`
}

func (m *QueryGetVncarbonResponse) Reset()         { *m = QueryGetVncarbonResponse{} }
func (m *QueryGetVncarbonResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetVncarbonResponse) ProtoMessage()    {}
func (*QueryGetVncarbonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_286c366297741c32, []int{1}
}
func (m *QueryGetVncarbonResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVncarbonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVncarbonResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVncarbonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVncarbonResponse.Merge(m, src)
}
func (m *QueryGetVncarbonResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVncarbonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVncarbonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVncarbonResponse proto.InternalMessageInfo

func (m *QueryGetVncarbonResponse) GetVncarbon() *Vncarbon {
	if m != nil {
		return m.Vncarbon
	}
	return nil
}

type QueryAllVncarbonRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVncarbonRequest) Reset()         { *m = QueryAllVncarbonRequest{} }
func (m *QueryAllVncarbonRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllVncarbonRequest) ProtoMessage()    {}
func (*QueryAllVncarbonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_286c366297741c32, []int{2}
}
func (m *QueryAllVncarbonRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVncarbonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVncarbonRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVncarbonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVncarbonRequest.Merge(m, src)
}
func (m *QueryAllVncarbonRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVncarbonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVncarbonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVncarbonRequest proto.InternalMessageInfo

func (m *QueryAllVncarbonRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllVncarbonResponse struct {
	Vncarbon   []*Vncarbon         `protobuf:"bytes,1,rep,name=Vncarbon,proto3" json:"Vncarbon,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVncarbonResponse) Reset()         { *m = QueryAllVncarbonResponse{} }
func (m *QueryAllVncarbonResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllVncarbonResponse) ProtoMessage()    {}
func (*QueryAllVncarbonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_286c366297741c32, []int{3}
}
func (m *QueryAllVncarbonResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVncarbonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVncarbonResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVncarbonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVncarbonResponse.Merge(m, src)
}
func (m *QueryAllVncarbonResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVncarbonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVncarbonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVncarbonResponse proto.InternalMessageInfo

func (m *QueryAllVncarbonResponse) GetVncarbon() []*Vncarbon {
	if m != nil {
		return m.Vncarbon
	}
	return nil
}

func (m *QueryAllVncarbonResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetVncarbonRequest)(nil), "faddat.vncarbon.vncarbon.QueryGetVncarbonRequest")
	proto.RegisterType((*QueryGetVncarbonResponse)(nil), "faddat.vncarbon.vncarbon.QueryGetVncarbonResponse")
	proto.RegisterType((*QueryAllVncarbonRequest)(nil), "faddat.vncarbon.vncarbon.QueryAllVncarbonRequest")
	proto.RegisterType((*QueryAllVncarbonResponse)(nil), "faddat.vncarbon.vncarbon.QueryAllVncarbonResponse")
}

func init() { proto.RegisterFile("vncarbon/query.proto", fileDescriptor_286c366297741c32) }

var fileDescriptor_286c366297741c32 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0x80, 0xbb, 0xf9, 0xf9, 0x7f, 0x7e, 0xb7, 0xe0, 0x61, 0x11, 0x5a, 0x8a, 0x04, 0x59, 0xc4,
	0xda, 0x0a, 0xbb, 0xb4, 0xde, 0x85, 0x0a, 0xda, 0xab, 0xf6, 0xe0, 0xa1, 0xb7, 0x4d, 0xb3, 0xc6,
	0x40, 0x9a, 0x4d, 0xbb, 0xdb, 0x62, 0x11, 0x2f, 0x3e, 0x81, 0xe0, 0x0b, 0x88, 0xbe, 0x8c, 0x37,
	0x0b, 0x5e, 0x3c, 0x4a, 0xeb, 0x83, 0x48, 0x93, 0x6d, 0xd2, 0x9a, 0x96, 0xd0, 0xdb, 0x90, 0x99,
	0x6f, 0xe6, 0x9b, 0x4c, 0x02, 0x77, 0x86, 0x7e, 0x87, 0xf5, 0x2d, 0xe1, 0xd3, 0xde, 0x80, 0xf7,
	0x47, 0x24, 0xe8, 0x0b, 0x25, 0x50, 0xf1, 0x9a, 0xd9, 0x36, 0x53, 0x64, 0x9e, 0x8c, 0x83, 0xd2,
	0xae, 0x23, 0x84, 0xe3, 0x71, 0xca, 0x02, 0x97, 0x32, 0xdf, 0x17, 0x8a, 0x29, 0x57, 0xf8, 0x32,
	0xe2, 0x4a, 0xd5, 0x8e, 0x90, 0x5d, 0x21, 0xa9, 0xc5, 0x24, 0x8f, 0x1a, 0xd2, 0x61, 0xcd, 0xe2,
	0x8a, 0xd5, 0x68, 0xc0, 0x1c, 0xd7, 0x0f, 0x8b, 0x75, 0x6d, 0x21, 0x9e, 0x1c, 0x4f, 0x09, 0x13,
	0xb8, 0x02, 0x0b, 0x97, 0x33, 0xb4, 0xc9, 0xd5, 0x95, 0xce, 0xb4, 0x78, 0x6f, 0xc0, 0xa5, 0x42,
	0xdb, 0xd0, 0x70, 0xed, 0x22, 0xd8, 0x03, 0x87, 0x5b, 0x2d, 0xc3, 0xb5, 0x71, 0x1b, 0x16, 0xd3,
	0xa5, 0x32, 0x10, 0xbe, 0xe4, 0xe8, 0x04, 0xfe, 0x9f, 0x3f, 0x0b, 0x89, 0x7c, 0x1d, 0x93, 0x75,
	0x6b, 0x91, 0x98, 0x8e, 0x19, 0xcc, 0xb4, 0x46, 0xc3, 0xf3, 0x7e, 0x6b, 0x9c, 0x43, 0x98, 0xac,
	0xa3, 0x9b, 0x1f, 0x90, 0x68, 0x77, 0x32, 0xdb, 0x9d, 0x44, 0x2f, 0x53, 0xef, 0x4e, 0x2e, 0x98,
	0xc3, 0x35, 0xdb, 0x5a, 0x20, 0xf1, 0x2b, 0xd0, 0xfe, 0x4b, 0x33, 0x56, 0xfa, 0xff, 0xd9, 0xd4,
	0x1f, 0x35, 0x97, 0x24, 0x8d, 0x50, 0xb2, 0x9c, 0x29, 0x19, 0x0d, 0x5f, 0xb4, 0xac, 0xbf, 0x1b,
	0xf0, 0x6f, 0x68, 0x89, 0x5e, 0x40, 0xe2, 0x84, 0x6a, 0xeb, 0x6d, 0xd6, 0x9c, 0xaf, 0x54, 0xdf,
	0x04, 0x89, 0x4c, 0x30, 0x7d, 0xf8, 0xf8, 0x7e, 0x32, 0x2a, 0xa8, 0x4c, 0x23, 0x96, 0xa6, 0x3e,
	0x9b, 0x24, 0xb8, 0x73, 0xed, 0x7b, 0xf4, 0x0c, 0x60, 0x7e, 0xde, 0xa5, 0xe1, 0x79, 0x99, 0x9e,
	0xe9, 0xfb, 0x66, 0x7a, 0xae, 0x38, 0x17, 0xae, 0x86, 0x9e, 0xfb, 0x08, 0x67, 0x7b, 0x9e, 0x9e,
	0xbd, 0x4d, 0x4c, 0x30, 0x9e, 0x98, 0xe0, 0x6b, 0x62, 0x82, 0xc7, 0xa9, 0x99, 0x1b, 0x4f, 0xcd,
	0xdc, 0xe7, 0xd4, 0xcc, 0xb5, 0x8f, 0x1c, 0x57, 0xdd, 0x0c, 0x2c, 0xd2, 0x11, 0xdd, 0x54, 0x9f,
	0xdb, 0x24, 0x54, 0xa3, 0x80, 0x4b, 0xeb, 0x5f, 0xf8, 0xbf, 0x1c, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xda, 0x76, 0x1f, 0xc6, 0xc4, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	Vncarbon(ctx context.Context, in *QueryGetVncarbonRequest, opts ...grpc.CallOption) (*QueryGetVncarbonResponse, error)
	VncarbonAll(ctx context.Context, in *QueryAllVncarbonRequest, opts ...grpc.CallOption) (*QueryAllVncarbonResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Vncarbon(ctx context.Context, in *QueryGetVncarbonRequest, opts ...grpc.CallOption) (*QueryGetVncarbonResponse, error) {
	out := new(QueryGetVncarbonResponse)
	err := c.cc.Invoke(ctx, "/faddat.vncarbon.vncarbon.Query/Vncarbon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VncarbonAll(ctx context.Context, in *QueryAllVncarbonRequest, opts ...grpc.CallOption) (*QueryAllVncarbonResponse, error) {
	out := new(QueryAllVncarbonResponse)
	err := c.cc.Invoke(ctx, "/faddat.vncarbon.vncarbon.Query/VncarbonAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	Vncarbon(context.Context, *QueryGetVncarbonRequest) (*QueryGetVncarbonResponse, error)
	VncarbonAll(context.Context, *QueryAllVncarbonRequest) (*QueryAllVncarbonResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Vncarbon(ctx context.Context, req *QueryGetVncarbonRequest) (*QueryGetVncarbonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vncarbon not implemented")
}
func (*UnimplementedQueryServer) VncarbonAll(ctx context.Context, req *QueryAllVncarbonRequest) (*QueryAllVncarbonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VncarbonAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Vncarbon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVncarbonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Vncarbon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faddat.vncarbon.vncarbon.Query/Vncarbon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Vncarbon(ctx, req.(*QueryGetVncarbonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VncarbonAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllVncarbonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VncarbonAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faddat.vncarbon.vncarbon.Query/VncarbonAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VncarbonAll(ctx, req.(*QueryAllVncarbonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "faddat.vncarbon.vncarbon.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Vncarbon",
			Handler:    _Query_Vncarbon_Handler,
		},
		{
			MethodName: "VncarbonAll",
			Handler:    _Query_VncarbonAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vncarbon/query.proto",
}

func (m *QueryGetVncarbonRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVncarbonRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVncarbonRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVncarbonResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVncarbonResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVncarbonResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Vncarbon != nil {
		{
			size, err := m.Vncarbon.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllVncarbonRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVncarbonRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVncarbonRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllVncarbonResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVncarbonResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVncarbonResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Vncarbon) > 0 {
		for iNdEx := len(m.Vncarbon) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Vncarbon[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetVncarbonRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVncarbonResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Vncarbon != nil {
		l = m.Vncarbon.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllVncarbonRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllVncarbonResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Vncarbon) > 0 {
		for _, e := range m.Vncarbon {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetVncarbonRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVncarbonRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVncarbonRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVncarbonResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVncarbonResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVncarbonResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vncarbon", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vncarbon == nil {
				m.Vncarbon = &Vncarbon{}
			}
			if err := m.Vncarbon.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVncarbonRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVncarbonRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVncarbonRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVncarbonResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVncarbonResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVncarbonResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vncarbon", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vncarbon = append(m.Vncarbon, &Vncarbon{})
			if err := m.Vncarbon[len(m.Vncarbon)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
